apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: katros250/url-shortener:0.1.0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value:

            - name: POSTGRES_DB_URL
              value:

            - name: POSTGRES_DB_USERNAME
              value:

            - name: POSTGRES_DB_PASSWORD
              value:
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 8081
  type: NodePort