scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['url-shortener-app:8081']
        labels:
          application: 'URL Shortener Application'